import { ResponseTiposCaracterizacion, ResponseListaProvincias, ResponseListaPaises, Proveedores, Proveedor, ResponseFacturador, ResponseClasificacion, ResponseCaracterizacion, ArticuloProveedor, ResponseListaCodigosProveedor, CodigoProveedor, ResponseValidacionGenerico, ResponseHacienda } from "../..";


export class ProveedoresViewModel {

    DatosBasicos: Proveedor;
    RspProvincias: ResponseListaProvincias;
    RspPaises: ResponseListaPaises;
    RspFacturador: ResponseFacturador;
    RspClasificacion: ResponseClasificacion;
    RpsTiposCaracterizacion: ResponseTiposCaracterizacion;
    RpsCaracterizacion: ResponseCaracterizacion;
    RspListaCodigosProveedor: ResponseListaCodigosProveedor;
    RspValidacionGenerico: ResponseValidacionGenerico;
    RspHacienda:ResponseHacienda;
    RspHaciendaRazSoc:ResponseHacienda;
    ListaArticuloProveedor: ArticuloProveedor[];
    ListaCodigosProveedor: CodigoProveedor[];    
    nombreTipCaract: string;
    action: string;
    habilitarGuardar: boolean;
    habilitarModificar: boolean;
    habilitarModificarDetalle: boolean;
    habilitarSoap: boolean;
    resul: string;
    loading: boolean;
    timer: any;
    hideSugerencias: boolean;
    validarLocalidad:boolean;
    validarEstadoLocalidad:boolean;
    validarDirSocial:boolean;
    validarEstadoDirSocial:boolean;
    validarRazSocial:boolean;
    validarRazSocialExiste:boolean;
    validarEstadoRazSocial:boolean;
    validarCif:boolean;
    validarCifExiste:boolean;
    validarEstadoCif:boolean;
    validarCodigoPostal: boolean;
    validarFormatoCodigoPostal: boolean;
    validarCodigoPostalFinal: boolean;
    validarEstadoCodigoPostal: boolean;
    validarAcuerdoComercial: boolean;
    validarFormatoAcuerdoComercial: boolean;
    validarEstadoAcuerdoComercial: boolean;
    validarImporteFijo: boolean;
    validarFormatoImporteFijo: boolean;
    validarEstadoImporteFijo: boolean;
    validarCodigoSap: boolean;
    validarCodigoSapFinal:boolean;
    validarEstadoCodigoSap:boolean;    
    validarFechaAlta: boolean;
    validarFormatoFechaAlta:boolean;        
    validarFechaBaja: boolean;
    validarFormatoFechaBaja:boolean;        
    validarFechaIni: boolean;
    validarFormatoFechaIni:boolean;        
    validarFechaFin: boolean;
    validarFormatoFechaFin:boolean;   
    validarFechaAltaFinal: boolean;
    validarFechaBajaFinal: boolean;
    validarFechaIniFinal: boolean;
    validarFechaFinFinal: boolean;
    validarFormatoCorreo1:boolean;
    validarFormatoCorreo2:boolean;
    validarFormatoCorreo3:boolean;
    validarEstadoCorreo1:boolean;
    validarEstadoCorreo2:boolean;
    validarEstadoCorreo3:boolean;
    pageTablaCaracterizaciones:number;
    fechaPlaceholder:string;
    

    constructor() {
        this.DatosBasicos = new Proveedor();
        this.RspProvincias = new ResponseListaProvincias();
        this.RspPaises = new ResponseListaPaises();
        this.RspFacturador = new ResponseFacturador();
        this.RspClasificacion = new ResponseClasificacion();
        this.RpsTiposCaracterizacion = new ResponseTiposCaracterizacion();
        this.RpsCaracterizacion = new ResponseCaracterizacion
        this.RspListaCodigosProveedor = new ResponseListaCodigosProveedor();
        this.RspValidacionGenerico = new ResponseValidacionGenerico();
        this.RspHacienda = new ResponseHacienda();
        this.RspHaciendaRazSoc =  new ResponseHacienda();
        this.ListaArticuloProveedor = [];
        this.ListaCodigosProveedor = [];
        this.nombreTipCaract = "";
        this.action = "";
        this.habilitarGuardar = false;
        this.habilitarModificar = true;
        this.habilitarModificarDetalle = true;
        this.habilitarSoap = true;
        this.resul = "";
        this.loading = false;
        this.timer = { search: { id: null, ms: 200 }, result: { id: null, ms: 200 } };
        this.hideSugerencias = true;
        this.validarLocalidad=true;
        this.validarEstadoLocalidad=true;
        this.validarDirSocial=true;
        this.validarEstadoDirSocial=true;
        this.validarRazSocial=true;
        this.validarRazSocialExiste=true;
        this.validarEstadoRazSocial=true;
        this.validarCif=true;
        this.validarEstadoCif=true;
        this.validarCifExiste=true;
        this.validarCodigoPostal = true;
        this.validarFormatoCodigoPostal = true;
        this.validarCodigoPostalFinal = true;
        this.validarEstadoCodigoPostal = true;
        this.validarAcuerdoComercial = true;
        this.validarEstadoAcuerdoComercial = true;
        this.validarFormatoAcuerdoComercial = true;
        this.validarImporteFijo = true;
        this.validarFormatoImporteFijo = true;
        this.validarEstadoImporteFijo = true;
        this.validarCodigoSap = true;
        this.validarCodigoSapFinal=true;
        this.validarEstadoCodigoSap = true;
        this.validarFechaAlta = true;
        this.validarFormatoFechaAlta=true;    
        this.validarFechaBaja = true;
        this.validarFormatoFechaBaja=true;   
        this.validarFechaIni = true;
        this.validarFormatoFechaIni=true;               
        this.validarFechaFin = true;
        this.validarFormatoFechaFin=true;               
        this.validarFechaAltaFinal = true;
        this.validarFechaBajaFinal = true;
        this.validarFechaIniFinal = true;
        this.validarFechaFinFinal = true;
        this.validarFormatoCorreo1 = true;
        this.validarFormatoCorreo2 = true;
        this.validarFormatoCorreo3 = true;
        this.validarEstadoCorreo1 = true;
        this.validarEstadoCorreo2 = true;
        this.validarEstadoCorreo3 = true;
        this.pageTablaCaracterizaciones=0;
        this.fechaPlaceholder="";
    }

}